title: Jason Marshall's Blog
tagline: Tech and Programming Blog
description: Thoughts about Software Development, Tooling, Processes, and Performance
author: Jason Marshall

social:
  name: Jason Marshall
  links:
    - https://github.com/jdmarshall

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image:
        path: /assets/images/og.png
        alt: Blog logo
        width: 128
        height: 128

