title: Jason Marshall's Blog
description: Tech and Programming Blog
author: Jason Marshall

social:
  name: Jason Marshall
  links:
    - https://github.com/jdmarshall

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image:
        path: /assets/images/og.png
        alt: Blog logo

